package com.xyrx.jcms.entity.sys;

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Database Table Remarks:
 *   标准代码表
 *
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table SysCode
 */
@Setter
@Getter
@Entity
@Table(name = "SYS_CODE")
public class SysCode {
    /**
     *   代码ID：ID规则CODE_TYPE + "-" + CODE
     *   SYS_CODE.CODE_ID
     */
    private String codeId;

    /**
     *   代码
     *   SYS_CODE.CODE
     */
    private String code;

    /**
     *   代码类别
     *   SYS_CODE.CODE_TYPE
     */
    private String codeType;

    /**
     *   代码值
     *   SYS_CODE.CODE_VALUE
     */
    private String codeValue;

    /**
     *   代码扩展信息1
     *   SYS_CODE.CODE_VALUE_1
     */
    private String codeValue1;

    /**
     *   代码扩展信息2
     *   SYS_CODE.CODE_VALUE_2
     */
    private String codeValue2;

    /**
     *   同一个TYPE下的展现顺序号
     *   SYS_CODE.ORDER_BY
     */
    private Short orderBy;

    /**
     *   父代码ID
     *   SYS_CODE.PAR_CODE_ID
     */
    private String parCodeId;

    /**
     *   有效标识：Y/N
     *   SYS_CODE.VALID_FLAG
     */
    private String validFlag;

    /**
     *   记录创建者
     *   SYS_CODE.CREATED_BY
     */
    private String createdBy;

    /**
     *   记录创建时间
     *   SYS_CODE.CREATED_TS
     */
    private Date createdTs;

    /**
     *   记录最后更新者
     *   SYS_CODE.LAST_UPD_BY
     */
    private String lastUpdBy;

    /**
     *   记录最后更新时间
     *   SYS_CODE.LAST_UPD_TS
     */
    private Date lastUpdTs;
}